# ================================================
# inventory.ini - Auto Generated by Terraform
# ================================================
[ec2]
${vm_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_key_path}
