# ================================================
# inventory.ini - Ansible Inventory File
# ================================================
# Best practice:
# - Gunakan grup [ec2] supaya mudah di-scale ke banyak server nanti
# - Simpan path SSH key relatif supaya portable

[ec2]
# Host yang kita provision di Milestone 1
devops-flask-vm ansible_host=3.80.214.193 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/devops-flask-key.pem
